# Generated by Django 5.1.2 on 2024-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
