# Generated by Django 5.1.2 on 2024-10-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_departamentos', '0001_initial'),
        ('gestao_funcionarios', '0002_alter_funcionario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_departamentos.departamento'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
